{% set name = "polyhedral-gravity-model" %}
{% set org = "esa" %}
{% set version = "3.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 14fe00afe5db3e3316862ca1f406c285d4871bdd18ae7652af73e468a6dcd286

build:
  script_env:
    - CMAKE_GENERATOR=Ninja
    - POLYHEDRAL_GRAVITY_PARALLELIZATION=OMP
    - BUILD_SHARED_LIBS=ON
    - _LIBCPP_DISABLE_AVAILABILITY=1  # [osx]
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [linux]
    - ninja
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - python
    - spdlog
    - xsimd >=11.0.0
    - thrust
    - pybind11
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - polyhedral_gravity
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/esa/polyhedral-gravity-model
  summary: Package to compute full gravity tensor of a given constant density polyhedron for arbitrary points according to the geodetic convention
  description: >
    The package polyhedral_gravity provides a simple-to-use interface for evaluating the full gravity tensor of a constant-density polyhedron at arbitrary given computation points according to the geodetic convention. The computation is based on the line integral approach by Tsoulis et al., which transforms the triple integral
    into a summation. The implementation relies on a fast, parallelized backbone in C++ capable of evaluating the gravity at thousands of computation points in a fraction of a second. The package includes the functionality to read a polyhedral mesh from files and transform it to fulfill the preconditions of Tsoulis' formulation.
  license: GPL-3.0-only AND AGPL-3.0-or-later
  license_family: GPL3
  license_file:
    - LICENSE
    - TetGen_LICENSE
  doc_url: https://esa.github.io/polyhedral-gravity-model/
  dev_url: https://github.com/esa/polyhedral-gravity-model

extra:
  recipe-maintainers:
    - schuhmaj
    - gomezzz
    - darioizzo
