{% set name = "polyhedral-gravity-model" %}
{% set org = "esa" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: fc6c5ed8fba6df5c8f94d5423b6d88731107ea625810eb731ab096f5a6e8a14e

build:
  script_env:
    - CMAKE_GENERATOR=Ninja
    - POLYHEDRAL_GRAVITY_PARALLELIZATION=OMP
    - BUILD_SHARED_LIBS=ON
    - _LIBCPP_DISABLE_AVAILABILITY=1  # [osx]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [linux]
    - ninja
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - python
    - spdlog
    - xsimd >=11.0.0
    - thrust
    - pybind11
    - pip
  run:
    - python

test:
  imports:
    - polyhedral_gravity
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/esa/polyhedral-gravity-model
  summary: Simple and fast evaluation of the polyhedral gravity model for a constant density polyhedron
  description: >
    The package polyhedral_gravity provides a simple to use interface for the evaluation of the full gravity tensor of a constant density polyhedron at given computation points. It is based on a fast, parallelized backbone in C++ capable of evaluating the gravity at thousands of computation points in the fraction of a second.
  license: GPL-3.0-only AND AGPL-3.0-or-later
  license_family: GPL3
  license_file:
    - LICENSE
    - TetGen_LICENSE
  doc_url: https://polyhedral-gravity-model-cpp.readthedocs.io/en/latest
  dev_url: https://github.com/esa/polyhedral-gravity-model

extra:
  recipe-maintainers:
    - schuhmaj
    - gomezzz
    - darioizzo
