{% set name = "polyhedral-gravity-model" %}
{% set org = "esa" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: eeb206a0fa1fb8e24269dcc40f09a89244e8ba53d00adcab5c7d894a16a80e23

build:
  script_env:
    - CMAKE_GENERATOR=Ninja
    - POLYHEDRAL_GRAVITY_PARALLELIZATION=OMP
    - BUILD_SHARED_LIBS=ON
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [linux]
    - ninja
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - python
    - spdlog
    - xsimd
    - thrust
    - pybind11
    - pip
  run:
    - python

test:
  imports:
    - polyhedral_gravity
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/esa/polyhedral-gravity-model
  summary: Simple and fast evaluation of the polyhedral gravity model for a constant density polyhedron
  description: >
    The package polyhedral_gravity provides a simple to use interface for the evaluation of the full gravity tensor of a constant density polyhedron at given computation points. It is based on a fast, parallelized backbone in C++ capable of evaluating the gravity at thousands of computation points in the fraction of a second.
  license: GPL-3.0-only AND AGPL-3.0-or-later
  license_family: GPL3
  license_file:
    - LICENSE
    - TetGen_LICENSE
  doc_url: https://polyhedral-gravity-model-cpp.readthedocs.io/en/latest
  dev_url: https://github.com/esa/polyhedral-gravity-model

extra:
  recipe-maintainers:
    - schuhmaj
    - gomezzz
    - darioizzo
